<img src="images/Picture0.png" width=200x />

# Notebook 10 - NumPy Intermediate

## Instructions
Read the material below and complete the exercises.

Material covered in this notebook:

- How to generate arrays from functions
- How to perform I/O with arrays
- Manipulating arrays
- More linear algebra

### Pre-requisites
Notebooks 01 - 05, 09

### Credits
Adapted from work of [J.R. Johansson](https://github.com/jrjohansson/scientific-python-lectures)


# Creating `numpy` arrays

Let's first import matplotlib and ensure that the plots are embedded nicely in the notebook.

In [ ]:
%matplotlib inline 

import matplotlib.pyplot as plt

In the previous numpy notebook, we learned how to create arrays from lists. Below we'll learn common functions for creating numpy arrays of specific forms.

### Exercise
Let's first import ``numpy`` as ``np``.

## Creating `numpy` arrays using array-generating functions

For larger arrays it is inpractical to initialize the data manually, using explicit Python lists. Instead we can use one of the many functions in `numpy` that generate arrays of different forms. Some of the more common are:

### arange
The `arange()` function is similar to the `range()` function and creates values using arguments start, stop, and step.

In [19]:
x = np.arange(0, 10, 1)
print(x.shape)
print(x)

(10,)
[0 1 2 3 4 5 6 7 8 9]


### Exercise
Create an array with values from -1 to 1, with step size 0.1.

### Exercise
Produce a plot of a sinusoid on the interval $[−\pi, \pi]$. Include a title and labels for the $x$- and $y$-axes. Remember that you can use the module `math`. Experiment with different step sizes to obtain a nice smooth graph. What is an optimal value? (*Hint:* Think pixels on your screen.)

Let's make our sinusoid graph better looking by changing our $x$-axis labels! The labels of the $x$-axis are called ticks. We use the function `plt.xticks`. Let's make sure the $x$-axis has labels at $-\pi$, $0$ and $\pi$.

In [ ]:
x = np.arange(-np.pi,np.pi,0.1)   # start,stop,step
y = np.sin(x)
plt.plot(x,y)
#plt.axhline(y=0)
plt.xlabel('x-values')
plt.ylabel('sin(x)')
plt.xticks((-np.pi, 0, np.pi), ('-$\pi$', '0', '$\pi$'))
plt.title('Plot of the Sine Function')
plt.show()

### Exercise
Produce a plot of the functions $f(x) = e^{-x/10} \sin(\pi x)$ and $g(x) = xe^{−x/3}$ over the interval $[0, 10]$. Include labels for the $x$- and $y$-axes, and a legend explaining which line is which plot.

### linspace and logspace
The `linspace()` and `logspace()` functions are used to create regularly-spaced points in the domain. These functions take three arguments: start, end, and number-of-elements. Unlike `arange()`, the end points are included in these functions. Let's look at specific examples:

In [2]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [3]:
np.logspace(0, 10, 10, base=np.e)

array([1.00000000e+00, 3.03773178e+00, 9.22781435e+00, 2.80316249e+01,
       8.51525577e+01, 2.58670631e+02, 7.85771994e+02, 2.38696456e+03,
       7.25095809e+03, 2.20264658e+04])

### Exercise
How is `np.linspace()` different from `np.arange()`? What does `np.logspace()` do?

### random data
The `numpy` package has different functions for generating random series. For a uniform distribution, the `rand()` function is used for populating an array of a specified size with numbers uniformly distributed in the $[0,1)$ interval.

In [4]:
np.random.rand(5, 5)

array([[0.37292118, 0.56689578, 0.40427832, 0.14939739, 0.40610223],
       [0.70313189, 0.68508353, 0.94167473, 0.62334677, 0.90333538],
       [0.80070198, 0.0391906 , 0.0661671 , 0.62722351, 0.53818059],
       [0.85838642, 0.9240972 , 0.44651482, 0.20572705, 0.50263113],
       [0.85584407, 0.31452846, 0.38103541, 0.77441872, 0.34765411]])

While the `randn()` function is used for populating an array of a given size with numbers from a Gaussian distribution of mean 0 and variance 1.

In [7]:
np.random.randn(5, 5)

array([[-0.19099303, -0.93587363,  0.07182065, -0.60231961, -0.34379036],
       [-1.56612482,  0.78048046,  2.0925645 , -0.26984681, -1.11966762],
       [ 0.60648762,  0.43194037, -0.75860021,  0.2631642 , -1.21930552],
       [-0.54617272,  2.56249274, -0.42194705, -0.19963629, -1.0935662 ],
       [-0.94574512,  0.41358917, -0.05798413, -2.02422902, -0.740418  ]])

### diag
Diagonal square matrices can be created directly using the `diag()` constructor. It takes a list as an argument for specifying the values of the diagonal elements. For example,

In [16]:
x = np.diag([1,2,3])
print(x.shape)
print(x)

(3, 3)
[[1 0 0]
 [0 2 0]
 [0 0 3]]


A diagonal matrix can also have an offset using the `k` keyword which defaults to 0. For example,

In [20]:
np.diag([1,2,3], k=1)

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

Notice how the offset made the shape of the matrix one size larger.

### zeros and ones
It is good practice to initialize the elements in an array when it is created, and often with 0, or 1. For this purpose, the `zeros()` and `ones()` functions are used. The required argument is a tuple representing the shape of the desired array, thus the double parentheses.

In [21]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

To copy the shape of another object, the `ones_like()` and the `zeros_like()` functions can be used.

In [23]:
y = np.random.randn(5,5)

np.ones_like(y)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros_like(y)

### Exercise
Using the `shape` property and the `zeros()` function, write an equivalent to `zeros_like()`.

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Exercise
Use the commands above to create the following matrices.

1. A $4\times4$ diagonal matrix with diagonal entries $1, 2, 3, 4$.

2. A $5\times 3$ matrix of all $1$s.

3. The vector $(1,1.2,1.4,1.6,1.8,2)$ using two different methods.

4. A vector of length $8$ with random entries drawn from a normal distribution with mean 1 and variance 1.

## Input/Output in `numpy`

### Reading comma-separated values (CSV)

A very common file format for data files is comma-separated values (CSV), or related formats such as TSV (tab-separated values). To read data from such files into Numpy arrays we can use the `numpy.genfromtxt` function. For example, 

In [ ]:
# On macOS and Linux uncomment the following line
# !head data/stockholm_td_adj2.csv
# On Windows use the following commands
!type data\stockholm_td_adj2.csv

In [ ]:
data = np.genfromtxt('./data/stockholm_td_adj.dat')

In [ ]:
data.shape

In [ ]:
fig, ax = plt.subplots(figsize=(14,4))
ax.plot(data[:,0]+data[:,1]/12.0+data[:,2]/365, data[:,5])
ax.axis('tight')
ax.set_title('temperatures in Stockholm')
ax.set_xlabel('year')
ax.set_ylabel('temperature (C)');

As shown in the Stockholm example, `genfromtxt` is useful to import data. The function splits each non-empty line into an array with proper data types.

However, a CSV file generally contains a tabular data where each row contains comma-separated values. The table may have a header which is an array of values assigned to each of the columns. It acts as a row header for the data. The columns may contain values belonging to different data structures. 

In [ ]:
# On macOS and Linux uncomment the following line
# !head data/stockholm_td_adj2.csv
# On Windows use the following commands
!type data\stockholm_td_adj2.csv

### Exercise
Try to read the above data using the filename only. 

`genfromtxt` returns NaN rows. It can be handled using `genfromtxt` keywords. We can use different delimiters, skip header rows, control the type of imported data, give columns of data names, etc.

For example, 
- the `delimiter` keyword is used to define how the splitting should take place. By default, `genfromtxt` assumes `delimiter=None`, meaning that the line is split along white spaces (including tabs). A comma-separated file (CSV) quite often uses a comma (,) or a semicolon (;) as delimiter.

- `dtype` is used to define the data type of the resulting array. float is the default value for the `dtype` keyword. If `dtype = None`, the dtypes will be determined by the contents of each column, individually.

- `skip_header` is used to skip at the beginning of the file. The default is `skip_header=0`.

- `names` is used to define the field names in a structured dtype. If `names=True`, the field names are read from the first line after the first `skip_header` lines.

For more details, see [here](https://numpy.org/doc/stable/reference/generated/numpy.genfromtxt.html). 

In [ ]:
data2 = np.genfromtxt(
    './data/stockholm_td_adj2.csv', 
    delimiter=',', # comma separated values
    names = True, # the field names are read from the first valid line
    dtype = None) # guess the dtype of each column
data2

Above array are said to have structured datatype, or, structured arrays. Indexing with the field name allows us to access (and modify) individual fields of a structured array:

In [ ]:
data2['Year']

Using `numpy.savetxt` we can store a Numpy array to a file in CSV format:

In [ ]:
M = np.random.rand(3,3)

M

In [ ]:
np.savetxt("random-matrix.csv", M)

In [ ]:
!cat random-matrix.csv

In [ ]:
np.savetxt("random-matrix.csv", M, fmt='%.5f') # fmt specifies the format

!cat random-matrix.csv

### Numpy's native file format

Useful when storing and reading back numpy array data. Use the functions `numpy.save` and `numpy.load`:

In [ ]:
np.save("random-matrix.npy", M)

!file random-matrix.npy

In [ ]:
np.load("random-matrix.npy")

## Manipulating arrays

## Advanced Indexing

### Index slicing

Index slicing is the technical name for the syntax `M[lower:upper:step]` to extract part of an array:

In [ ]:
A = np.array([1,2,3,4,5])
A

In [ ]:
A[1:3]

We can omit any of the three parameters in `M[lower:upper:step]`:

In [ ]:
A[:3] # first three elements

In [ ]:
A[3:] # elements from index 3

In [ ]:
A[::] # lower, upper, step all take the default values

### Exercise
Use step parameter to obtain values at even indices of the array A.


### Assigning with slices

Array slices are *mutable*: if they are assigned a new value the original array from which the slice was extracted is modified:

In [ ]:
A[1:3] = [-2,-3]

A

Negative indices counts from the end of the array (positive index from the begining):

In [ ]:
A = np.array([1,2,3,4,5])

In [ ]:
A[-1] # the last element in the array

In [ ]:
A[-3:] # the last three elements

Index slicing works exactly the same way for multidimensional arrays:

In [ ]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])

A

In [ ]:
# a block from the original array
A[1:4, 1:4]

In [ ]:
# strides
A[::2, ::2]

### Exercise
Using the matrix $A$, write code to print:
1. `array([ 1, 11, 21, 31, 41])`
2. `array([[ 1,  3], [11, 13], [21, 23], [31, 33], [41, 43]])` 
3. `array([[11, 13], [31, 33]])`
4. `array([[33, 34], [43, 44]])`

### Fancy indexing

Fancy indexing is the name for when an array or list is used in-place of an index: 

In [ ]:
row_indices = [1, 2, 3]
A[row_indices]

In [ ]:
col_indices = [1, 2, -1] # remember, index -1 means the last element
A[row_indices, col_indices]

We can also use index masks: If the index mask is an Numpy array of data type `bool`, then an element is selected (True) or not (False) depending on the value of the index mask at the position of each element: 

In [ ]:
B = np.array([n for n in range(5)])
B

In [ ]:
row_mask = np.array([True, False, True, False, False])
B[row_mask]

In [ ]:
# same thing
row_mask = np.array([1,0,1,0,0], dtype=bool)
B[row_mask]

This feature is very useful to conditionally select elements from an array, using for example comparison operators:

In [ ]:
x = np.arange(0, 10, 0.5)
x

In [ ]:
mask = (5 < x) * (x < 7.5)

mask

In [ ]:
x[mask]

### Exercise
Create a $5\times 5$ matrix with entries drawn from a uniform distribution on $[-1,1]$. Using a mask, print only the positive entries of the matrix.



## Linear algebra

### Data processing

Often it is useful to store datasets in Numpy arrays. Numpy provides a number of functions to calculate statistics of datasets in arrays. 

For example, let's calculate some properties from the Stockholm temperature dataset used above.

In [ ]:
# reminder, the tempeature dataset is stored in the data variable:
np.shape(data)

### mean

In [ ]:
# the temperature data is in column 3
np.mean(data[:,3])

The daily mean temperature in Stockholm over the last 200 years has been about 6.2 C.

### standard deviations and variance

In [ ]:
np.std(data[:,3]), np.var(data[:,3])

### min and max

In [ ]:
# lowest daily average temperature
data[:,3].min()

In [ ]:
# highest daily average temperature
data[:,3].max()

## Computations on subsets of arrays

We can compute with subsets of the data in an array using indexing, fancy indexing, and the other methods of extracting data from an array (described above).

For example, let's go back to the temperature dataset:

In [ ]:
# On macOS and Linux uncomment the following line
# !head -n 3 data/stockholm_td_adj.csv
# On Windows use the following commands
!type data\stockholm_td_adj.csv

The dataformat is: year, month, day, daily average temperature, low, high, location.

If we are interested in the average temperature only in a particular month, say February, then we can create a index mask and use it to select only the data for that month using:

In [ ]:
np.unique(data[:,1]) # the month column takes values from 1 to 12

In [ ]:
mask_feb = data[:,1] == 2

In [ ]:
# the temperature data is in column 3
np.mean(data[mask_feb,3])

### Exercise
1.   Extract the mean monthly average temperatures for each month of the year.
2.   Plot the extracted mean values by months. (Remember to add the proper month labeling)


In [ ]:
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']

## Calculations with higher-dimensional data

When functions such as `min`, `max`, etc. are applied to a multidimensional arrays, it is sometimes useful to apply the calculation to the entire array, and sometimes only on a row or column basis. Using the `axis` argument we can specify how these functions should behave: 

In [ ]:
m = np.random.rand(3,3)
m

In [ ]:
# global max
m.max()

In [ ]:
# max in each column
m.max(axis=0)

In [ ]:
# max in each row
m.max(axis=1)

Many other functions and methods in the `array` and `matrix` classes accept the same (optional) `axis` keyword argument.

## Copying

To achieve high performance, assignments in Python usually do not copy the underlaying objects. This is important for example when objects are passed between functions, to avoid an excessive amount of memory copying when it is not necessary (technical term: pass by reference). 

In [ ]:
A = np.array([[1, 2], [3, 4]])

A

In [ ]:
# now B is referring to the same array data as A 
B = A 

In [ ]:
# changing B affects A
B[0,0] = 10

B

In [ ]:
A

If we want to avoid this behavior, so that when we get a new completely independent object `B` copied from `A`, then we need to use the function `copy`:

In [ ]:
B = np.copy(A)

In [ ]:
# now, if we modify B, A is not affected
B[0,0] = -5

B

In [ ]:
A

## Iterating over array elements

Generally, we want to avoid iterating over the elements of arrays whenever we can (at all costs). The reason is that in a interpreted language like Python (or MATLAB), iterations are really slow compared to vectorized operations. 

However, sometimes iterations are unavoidable. For such cases, the Python `for` loop is the most convenient way to iterate over an array:

In [ ]:
v = np.array([1,2,3,4])

for element in v:
    print(element)

In [ ]:
M = np.array([[1,2], [3,4]])

for row in M:
    print("row", row)
    
    for element in row:
        print(element)

When we need to iterate over each element of an array and modify its elements, it is convenient to use the `enumerate` function to obtain both the element and its index in the `for` loop: 

In [ ]:
for row_idx, row in enumerate(M):
    print("row_idx", row_idx, "row", row)
    
    for col_idx, element in enumerate(row):
        print("col_idx", col_idx, "element", element)
       
        # update the matrix M: square each element
        M[row_idx, col_idx] = element ** 2

In [ ]:
# each element in M is now squared
M

### Exercise
Create a $5\times 5$ matrix with entries drawn from a uniform distribution on $[-1,1]$. Using a loop, print only the positive entries of the matrix.

## Using arrays in conditions

When using arrays in conditions,for example `if` statements and other boolean expressions, one needs to use `any` or `all`, which requires that any or all elements in the array evalutes to `True`:

In [ ]:
M

In [ ]:
if (M > 5).any():
    print("at least one element in M is larger than 5")
else:
    print("no element in M is larger than 5")

In [ ]:
if (M > 5).all():
    print("all elements in M are larger than 5")
else:
    print("all elements in M are not larger than 5")

<hr>
<font face="verdana" style="font-size:30px" color="blue">---------- Optional Advanced Material ----------</font>

## Reshaping, resizing and stacking arrays

The shape of an Numpy array can be modified without copying the underlaying data, which makes it a fast operation even for large arrays.

In [ ]:
A

In [ ]:
n, m = A.shape

In [ ]:
B = A.reshape((1,n*m))
B

In [ ]:
B[0,0:5] = 5 # modify the array

B

In [ ]:
A # and the original variable is also changed. B is only a different view of the same data

We can also use the function `flatten` to make a higher-dimensional array into a vector. But this function creates a copy of the data.

In [ ]:
B = A.flatten()

B

In [ ]:
B[0:5] = 10

B

In [ ]:
A # now A has not changed, because B's data is a copy of A's, not refering to the same data

## Stacking and repeating arrays

Using functions `repeat`, `tile`, `vstack`, `hstack`, and `concatenate` we can create larger vectors and matrices from smaller ones:

### tile and repeat

In [ ]:
a = np.array([[1, 2], [3, 4]])

In [ ]:
# repeat each element 3 times
np.repeat(a, 3)

In [ ]:
# tile the matrix 3 times 
np.tile(a, 3)

### concatenate

In [ ]:
b = np.array([[5, 6]])

In [ ]:
np.concatenate((a, b), axis=0)

In [ ]:
np.concatenate((a, b.T), axis=1)

### hstack and vstack

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b.T))

## Mini-projects

### Newton's method

This problem has three parts: 

* Part 1: [Newton's Method](https://en.wikipedia.org/wiki/Newton%27s_method) is a root finding method that uses linear approximation. In particular, we guess a solution $x_0$ of the equation $f(x)= 0$, compute the linear approximation of $f(x)$ at $x_0$ and then find the x-intercept of the linear approximation. The general scheme of Newton's method may be written as: 
$$ x_{n+1} = x_n - \dfrac{f(x_n)}{f'(x_n)} $$ for $n=0,1, 2, ...$. The computation is repeated until $f(x_n)$ is close enough to zero. More precisely, we test if $|f(x_n)|< \epsilon$ , with $\epsilon$ being a small number. Write a function that returns an approximation of a solution of  $f(x)=0$ by Newton's method. Make sure that your function prints out an array containing the approximations. 
    
* Part 2: Let $f(x)= x^2- 9$. Using the function from Part 1, calculate an approximation for the solution of $f(x)=0$ using $x_0= 1000$ and $\epsilon= 0.01$
    
* Part 3: Create a Figure with two subplots, one next to the other. 
    * First plot: Plot the function $f(x)$ using `x=np.arange(0, 10,1)`. You should label where the solution to $f(x)=0$ is at, i.e. label the point $(3,0)$. Draw a horizontal line at $y =0$, you can use `plt.hlines()`.
    * Second plot: Plot the array from Part 2. 
    
    Make sure each graph has a title, labels, and correct limits. 

### Euler's method for solving ordinary differential equation.

For a first order ordinary differential equation, 
$$\frac{dS(t)}{dt} = F(t, S(t))$$
the linear approximation of $S(t)$ around $t_j$ at $t_{j+1}$ is called the *Explicit Euler Formula* :
$$ S(t_{j+1})= S(t_j) + hF(t_j, S(t_j))$$
where $h = t_{j+1} - t_j$ is a stepsize of the interval $[t_0, t_f]$.
Given initial value of $S_0 = S(t_0)$, we can use the formula to integrate the states up to $S(t_f)$. These $S(t)$ values are an approximated solution of the differential equation.

Consider the differential equation 
$$\frac{df(t)}{dt} = e^{-t} $$ with initial condition $f(0)=−1$.  Approximate the solution to this initial value problem between 0 and 1 in increments of 0.01 using the Euler's method. Plot the approximated solution with the exact solution. Note that the exact solution is $f(t)=-e^{-t}$.

### Improve your *Numpy Basics* mini-projects

Refine/improve your solutions to the Mini-projects at the end of the *Numpy Basics* notebook using things learned in this notebook.